version: 1
accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
  - name: bob
    coins: ["10000token", "100000000stake"]
validators:
  - name: alice
    bonded: "100000000stake"
genesis:
  chain_id: "oracle-consumer"
  app_state:
    gov:
      params:
        voting_period: "40s"
    pricefeed:
      params:
        source_channel: "channel-0"
      symbol_requests:
        [{ "symbol": "BAND", "oracle_script_id": 396, "block_interval": 40 }]
client:
  openapi:
    path: "docs/static/openapi.yml"
  typescript:
    path: "ts-client"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
