// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consumer/pricefeed/params.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	AskCount      uint64                                   `protobuf:"varint,1,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	MinCount      uint64                                   `protobuf:"varint,2,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	MinDsCount    uint64                                   `protobuf:"varint,3,opt,name=min_ds_count,json=minDsCount,proto3" json:"min_ds_count,omitempty"`
	PrepareGasA   uint64                                   `protobuf:"varint,4,opt,name=prepare_gas_a,json=prepareGasA,proto3" json:"prepare_gas_a,omitempty"`
	PrepareGasB   uint64                                   `protobuf:"varint,5,opt,name=prepare_gas_b,json=prepareGasB,proto3" json:"prepare_gas_b,omitempty"`
	ExecuteGasA   uint64                                   `protobuf:"varint,6,opt,name=execute_gas_a,json=executeGasA,proto3" json:"execute_gas_a,omitempty"`
	ExecuteGasB   uint64                                   `protobuf:"varint,7,opt,name=execute_gas_b,json=executeGasB,proto3" json:"execute_gas_b,omitempty"`
	SourceChannel uint64                                   `protobuf:"varint,8,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	FeeLimit      github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,9,rep,name=fee_limit,json=feeLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fee_limit"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_01d8ef28bf5a306c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetAskCount() uint64 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

func (m *Params) GetMinCount() uint64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *Params) GetMinDsCount() uint64 {
	if m != nil {
		return m.MinDsCount
	}
	return 0
}

func (m *Params) GetPrepareGasA() uint64 {
	if m != nil {
		return m.PrepareGasA
	}
	return 0
}

func (m *Params) GetPrepareGasB() uint64 {
	if m != nil {
		return m.PrepareGasB
	}
	return 0
}

func (m *Params) GetExecuteGasA() uint64 {
	if m != nil {
		return m.ExecuteGasA
	}
	return 0
}

func (m *Params) GetExecuteGasB() uint64 {
	if m != nil {
		return m.ExecuteGasB
	}
	return 0
}

func (m *Params) GetSourceChannel() uint64 {
	if m != nil {
		return m.SourceChannel
	}
	return 0
}

func (m *Params) GetFeeLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeeLimit
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "consumer.pricefeed.Params")
}

func init() { proto.RegisterFile("consumer/pricefeed/params.proto", fileDescriptor_01d8ef28bf5a306c) }

var fileDescriptor_01d8ef28bf5a306c = []byte{
	// 377 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xb1, 0x6e, 0xe2, 0x30,
	0x1c, 0xc6, 0x93, 0x83, 0xe3, 0xc0, 0x1c, 0x37, 0x44, 0x37, 0xe4, 0x38, 0x29, 0x41, 0x48, 0x27,
	0xb1, 0x5c, 0x5c, 0xda, 0x4e, 0xdd, 0x1a, 0x2a, 0x75, 0xe9, 0x50, 0x31, 0x76, 0x89, 0x1c, 0xf3,
	0x27, 0x58, 0x60, 0x3b, 0x8a, 0x93, 0x8a, 0x3e, 0x43, 0x97, 0x8e, 0x1d, 0x3b, 0xf7, 0x49, 0x18,
	0x19, 0x3b, 0xb5, 0x15, 0xbc, 0x48, 0x15, 0x3b, 0x20, 0xc4, 0x94, 0xe4, 0xfb, 0xfd, 0xf2, 0x0d,
	0x9f, 0x8d, 0x7c, 0x2a, 0x85, 0x2a, 0x38, 0x64, 0x38, 0xcd, 0x18, 0x85, 0x29, 0xc0, 0x04, 0xa7,
	0x24, 0x23, 0x5c, 0x05, 0x69, 0x26, 0x73, 0xe9, 0x38, 0x3b, 0x21, 0xd8, 0x0b, 0xdd, 0xdf, 0x89,
	0x4c, 0xa4, 0xc6, 0xb8, 0x7c, 0x33, 0x66, 0xd7, 0xa3, 0x52, 0x71, 0xa9, 0x70, 0x4c, 0x14, 0xe0,
	0xfb, 0x61, 0x0c, 0x39, 0x19, 0x62, 0x2a, 0x99, 0x30, 0xbc, 0xff, 0x58, 0x43, 0x8d, 0x5b, 0x5d,
	0xed, 0xfc, 0x45, 0x2d, 0xa2, 0xe6, 0x11, 0x95, 0x85, 0xc8, 0x5d, 0xbb, 0x67, 0x0f, 0xea, 0xe3,
	0x26, 0x51, 0xf3, 0x51, 0xf9, 0x5d, 0x42, 0xce, 0x44, 0x05, 0xbf, 0x19, 0xc8, 0x99, 0x30, 0xb0,
	0x87, 0x7e, 0x96, 0x70, 0xa2, 0x2a, 0x5e, 0xd3, 0x1c, 0x71, 0x26, 0xae, 0x94, 0x31, 0xfa, 0xa8,
	0x93, 0x66, 0x90, 0x92, 0x0c, 0xa2, 0x84, 0xa8, 0x88, 0xb8, 0x75, 0xad, 0xb4, 0xab, 0xf0, 0x9a,
	0xa8, 0xcb, 0x63, 0x27, 0x76, 0xbf, 0x1f, 0x3b, 0x61, 0xe9, 0xc0, 0x12, 0x68, 0x91, 0xef, 0x7a,
	0x1a, 0xc6, 0xa9, 0xc2, 0x5d, 0xcf, 0xa1, 0x13, 0xbb, 0x3f, 0x8e, 0x9d, 0xd0, 0xf9, 0x87, 0x7e,
	0x29, 0x59, 0x64, 0x14, 0x22, 0x3a, 0x23, 0x42, 0xc0, 0xc2, 0x6d, 0x6a, 0xa9, 0x63, 0xd2, 0x91,
	0x09, 0x9d, 0x19, 0x6a, 0x4d, 0x01, 0xa2, 0x05, 0xe3, 0x2c, 0x77, 0x5b, 0xbd, 0xda, 0xa0, 0x7d,
	0xfa, 0x27, 0x30, 0x8b, 0x06, 0xe5, 0xa2, 0x41, 0xb5, 0x68, 0x30, 0x92, 0x4c, 0x84, 0x27, 0xab,
	0x77, 0xdf, 0x7a, 0xfd, 0xf0, 0x07, 0x09, 0xcb, 0x67, 0x45, 0x1c, 0x50, 0xc9, 0x71, 0x35, 0xbf,
	0x79, 0xfc, 0x57, 0x93, 0x39, 0xce, 0x1f, 0x52, 0x50, 0xfa, 0x07, 0x35, 0x6e, 0x4e, 0x01, 0x6e,
	0xca, 0xf2, 0x8b, 0xfa, 0xf3, 0x8b, 0x6f, 0x85, 0xe7, 0xab, 0x8d, 0x67, 0xaf, 0x37, 0x9e, 0xfd,
	0xb9, 0xf1, 0xec, 0xa7, 0xad, 0x67, 0xad, 0xb7, 0x9e, 0xf5, 0xb6, 0xf5, 0xac, 0xbb, 0xee, 0xfe,
	0x4a, 0x2c, 0x0f, 0x2e, 0x85, 0xee, 0x8a, 0x1b, 0xfa, 0x28, 0xcf, 0xbe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xf7, 0x5e, 0xc6, 0xfe, 0x37, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeLimit) > 0 {
		for iNdEx := len(m.FeeLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.SourceChannel != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.SourceChannel))
		i--
		dAtA[i] = 0x40
	}
	if m.ExecuteGasB != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ExecuteGasB))
		i--
		dAtA[i] = 0x38
	}
	if m.ExecuteGasA != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.ExecuteGasA))
		i--
		dAtA[i] = 0x30
	}
	if m.PrepareGasB != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PrepareGasB))
		i--
		dAtA[i] = 0x28
	}
	if m.PrepareGasA != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PrepareGasA))
		i--
		dAtA[i] = 0x20
	}
	if m.MinDsCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinDsCount))
		i--
		dAtA[i] = 0x18
	}
	if m.MinCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MinCount))
		i--
		dAtA[i] = 0x10
	}
	if m.AskCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.AskCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AskCount != 0 {
		n += 1 + sovParams(uint64(m.AskCount))
	}
	if m.MinCount != 0 {
		n += 1 + sovParams(uint64(m.MinCount))
	}
	if m.MinDsCount != 0 {
		n += 1 + sovParams(uint64(m.MinDsCount))
	}
	if m.PrepareGasA != 0 {
		n += 1 + sovParams(uint64(m.PrepareGasA))
	}
	if m.PrepareGasB != 0 {
		n += 1 + sovParams(uint64(m.PrepareGasB))
	}
	if m.ExecuteGasA != 0 {
		n += 1 + sovParams(uint64(m.ExecuteGasA))
	}
	if m.ExecuteGasB != 0 {
		n += 1 + sovParams(uint64(m.ExecuteGasB))
	}
	if m.SourceChannel != 0 {
		n += 1 + sovParams(uint64(m.SourceChannel))
	}
	if len(m.FeeLimit) > 0 {
		for _, e := range m.FeeLimit {
			l = e.Size()
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskCount", wireType)
			}
			m.AskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCount", wireType)
			}
			m.MinCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinDsCount", wireType)
			}
			m.MinDsCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinDsCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareGasA", wireType)
			}
			m.PrepareGasA = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareGasA |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareGasB", wireType)
			}
			m.PrepareGasB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareGasB |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGasA", wireType)
			}
			m.ExecuteGasA = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGasA |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGasB", wireType)
			}
			m.ExecuteGasB = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGasB |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			m.SourceChannel = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SourceChannel |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeLimit = append(m.FeeLimit, types.Coin{})
			if err := m.FeeLimit[len(m.FeeLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
