// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consumer/pricefeed/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateRequestInterval struct {
	Symbol         string                                   `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OracleScriptId uint64                                   `protobuf:"varint,2,opt,name=oracle_script_id,json=oracleScriptId,proto3" json:"oracle_script_id,omitempty"`
	FeeLimit       github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=fee_limit,json=feeLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fee_limit"`
	BlockInterval  uint64                                   `protobuf:"varint,4,opt,name=block_interval,json=blockInterval,proto3" json:"block_interval,omitempty"`
	Sender         string                                   `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgCreateRequestInterval) Reset()         { *m = MsgCreateRequestInterval{} }
func (m *MsgCreateRequestInterval) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRequestInterval) ProtoMessage()    {}
func (*MsgCreateRequestInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f93295a654eb1b, []int{0}
}
func (m *MsgCreateRequestInterval) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRequestInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRequestInterval.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRequestInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRequestInterval.Merge(m, src)
}
func (m *MsgCreateRequestInterval) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRequestInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRequestInterval.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRequestInterval proto.InternalMessageInfo

func (m *MsgCreateRequestInterval) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *MsgCreateRequestInterval) GetOracleScriptId() uint64 {
	if m != nil {
		return m.OracleScriptId
	}
	return 0
}

func (m *MsgCreateRequestInterval) GetFeeLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeeLimit
	}
	return nil
}

func (m *MsgCreateRequestInterval) GetBlockInterval() uint64 {
	if m != nil {
		return m.BlockInterval
	}
	return 0
}

func (m *MsgCreateRequestInterval) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgCreateRequestIntervalResponse struct {
	RequestIntervalId uint64 `protobuf:"varint,1,opt,name=request_interval_id,json=requestIntervalId,proto3" json:"request_interval_id,omitempty"`
}

func (m *MsgCreateRequestIntervalResponse) Reset()         { *m = MsgCreateRequestIntervalResponse{} }
func (m *MsgCreateRequestIntervalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateRequestIntervalResponse) ProtoMessage()    {}
func (*MsgCreateRequestIntervalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82f93295a654eb1b, []int{1}
}
func (m *MsgCreateRequestIntervalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateRequestIntervalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateRequestIntervalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateRequestIntervalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateRequestIntervalResponse.Merge(m, src)
}
func (m *MsgCreateRequestIntervalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateRequestIntervalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateRequestIntervalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateRequestIntervalResponse proto.InternalMessageInfo

func (m *MsgCreateRequestIntervalResponse) GetRequestIntervalId() uint64 {
	if m != nil {
		return m.RequestIntervalId
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCreateRequestInterval)(nil), "consumer.pricefeed.MsgCreateRequestInterval")
	proto.RegisterType((*MsgCreateRequestIntervalResponse)(nil), "consumer.pricefeed.MsgCreateRequestIntervalResponse")
}

func init() { proto.RegisterFile("consumer/pricefeed/tx.proto", fileDescriptor_82f93295a654eb1b) }

var fileDescriptor_82f93295a654eb1b = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0xe3, 0xed, 0xb2, 0x62, 0x8d, 0x58, 0x81, 0xf9, 0x50, 0x08, 0x52, 0x36, 0x5a, 0x09,
	0x29, 0x07, 0xb0, 0xd9, 0x65, 0x9f, 0xa0, 0x3d, 0x55, 0xa2, 0x97, 0x70, 0xe3, 0x12, 0x25, 0xce,
	0x34, 0xb5, 0x9a, 0xc4, 0xc1, 0x76, 0xab, 0x56, 0xdc, 0x90, 0xb8, 0xf3, 0x1c, 0x3c, 0x49, 0x8f,
	0x3d, 0x72, 0x02, 0xd4, 0xbe, 0x08, 0x8a, 0x93, 0x56, 0x54, 0xd0, 0xc3, 0x9e, 0xec, 0x99, 0xff,
	0x8c, 0xe7, 0x37, 0xe3, 0xc1, 0x2f, 0xb9, 0xac, 0xf4, 0xac, 0x04, 0xc5, 0x6a, 0x25, 0x38, 0x8c,
	0x01, 0x32, 0x66, 0x16, 0xb4, 0x56, 0xd2, 0x48, 0x42, 0x76, 0x22, 0xdd, 0x8b, 0xde, 0xd3, 0x5c,
	0xe6, 0xd2, 0xca, 0xac, 0xb9, 0xb5, 0x91, 0x9e, 0xcf, 0xa5, 0x2e, 0xa5, 0x66, 0x69, 0xa2, 0x81,
	0xcd, 0xaf, 0x53, 0x30, 0xc9, 0x35, 0xe3, 0x52, 0x54, 0xad, 0x7e, 0xf5, 0xf5, 0x04, 0xbb, 0x23,
	0x9d, 0x0f, 0x14, 0x24, 0x06, 0x22, 0xf8, 0x34, 0x03, 0x6d, 0x86, 0x95, 0x01, 0x35, 0x4f, 0x0a,
	0xf2, 0x1c, 0x9f, 0xe9, 0x65, 0x99, 0xca, 0xc2, 0x45, 0x01, 0x0a, 0xcf, 0xa3, 0xce, 0x22, 0x21,
	0x7e, 0x24, 0x55, 0xc2, 0x0b, 0x88, 0x35, 0x57, 0xa2, 0x36, 0xb1, 0xc8, 0xdc, 0x93, 0x00, 0x85,
	0xa7, 0xd1, 0x45, 0xeb, 0xff, 0x60, 0xdd, 0xc3, 0x8c, 0x4c, 0xf0, 0xf9, 0x18, 0x20, 0x2e, 0x44,
	0x29, 0x8c, 0xdb, 0x0b, 0x7a, 0xe1, 0x83, 0x9b, 0x17, 0xb4, 0x45, 0xa2, 0x0d, 0x12, 0xed, 0x90,
	0xe8, 0x40, 0x8a, 0xaa, 0xff, 0x76, 0xf5, 0xf3, 0xd2, 0xf9, 0xfe, 0xeb, 0x32, 0xcc, 0x85, 0x99,
	0xcc, 0x52, 0xca, 0x65, 0xc9, 0x3a, 0xfe, 0xf6, 0x78, 0xa3, 0xb3, 0x29, 0x33, 0xcb, 0x1a, 0xb4,
	0x4d, 0xd0, 0xd1, 0xfd, 0x31, 0xc0, 0xfb, 0xe6, 0x71, 0xf2, 0x0a, 0x5f, 0xa4, 0x85, 0xe4, 0xd3,
	0x58, 0x74, 0xf4, 0xee, 0xa9, 0x25, 0x7a, 0x68, 0xbd, 0x07, 0x2d, 0x41, 0x95, 0x81, 0x72, 0xef,
	0x75, 0x2d, 0x59, 0xeb, 0x2a, 0xc2, 0xc1, 0xb1, 0x31, 0x44, 0xa0, 0x6b, 0x59, 0x69, 0x20, 0x14,
	0x3f, 0x51, 0xad, 0xb4, 0x2f, 0xd2, 0x74, 0x8e, 0x6c, 0x9d, 0xc7, 0xea, 0x30, 0x6b, 0x98, 0xdd,
	0x7c, 0x41, 0xb8, 0x37, 0xd2, 0x39, 0xf9, 0x8c, 0x9f, 0xfd, 0x7f, 0xbe, 0xaf, 0xe9, 0xbf, 0xff,
	0x48, 0x8f, 0x61, 0x78, 0xb7, 0x77, 0x89, 0xde, 0x41, 0xf7, 0x6f, 0x57, 0x1b, 0x1f, 0xad, 0x37,
	0x3e, 0xfa, 0xbd, 0xf1, 0xd1, 0xb7, 0xad, 0xef, 0xac, 0xb7, 0xbe, 0xf3, 0x63, 0xeb, 0x3b, 0x1f,
	0xbd, 0xfd, 0x86, 0x2d, 0xfe, 0xde, 0xb1, 0x66, 0xba, 0xe9, 0x99, 0xdd, 0x8e, 0x77, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x6e, 0xcf, 0x43, 0x0a, 0x86, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateRequestInterval(ctx context.Context, in *MsgCreateRequestInterval, opts ...grpc.CallOption) (*MsgCreateRequestIntervalResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateRequestInterval(ctx context.Context, in *MsgCreateRequestInterval, opts ...grpc.CallOption) (*MsgCreateRequestIntervalResponse, error) {
	out := new(MsgCreateRequestIntervalResponse)
	err := c.cc.Invoke(ctx, "/consumer.pricefeed.Msg/CreateRequestInterval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateRequestInterval(context.Context, *MsgCreateRequestInterval) (*MsgCreateRequestIntervalResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateRequestInterval(ctx context.Context, req *MsgCreateRequestInterval) (*MsgCreateRequestIntervalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRequestInterval not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateRequestInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateRequestInterval)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateRequestInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.pricefeed.Msg/CreateRequestInterval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateRequestInterval(ctx, req.(*MsgCreateRequestInterval))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consumer.pricefeed.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRequestInterval",
			Handler:    _Msg_CreateRequestInterval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consumer/pricefeed/tx.proto",
}

func (m *MsgCreateRequestInterval) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRequestInterval) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRequestInterval) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x2a
	}
	if m.BlockInterval != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockInterval))
		i--
		dAtA[i] = 0x20
	}
	if len(m.FeeLimit) > 0 {
		for iNdEx := len(m.FeeLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.OracleScriptId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OracleScriptId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Symbol) > 0 {
		i -= len(m.Symbol)
		copy(dAtA[i:], m.Symbol)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Symbol)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateRequestIntervalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateRequestIntervalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateRequestIntervalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestIntervalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestIntervalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateRequestInterval) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Symbol)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.OracleScriptId != 0 {
		n += 1 + sovTx(uint64(m.OracleScriptId))
	}
	if len(m.FeeLimit) > 0 {
		for _, e := range m.FeeLimit {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.BlockInterval != 0 {
		n += 1 + sovTx(uint64(m.BlockInterval))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateRequestIntervalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestIntervalId != 0 {
		n += 1 + sovTx(uint64(m.RequestIntervalId))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateRequestInterval) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRequestInterval: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRequestInterval: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Symbol", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Symbol = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptId", wireType)
			}
			m.OracleScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeLimit = append(m.FeeLimit, types.Coin{})
			if err := m.FeeLimit[len(m.FeeLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockInterval", wireType)
			}
			m.BlockInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateRequestIntervalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateRequestIntervalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateRequestIntervalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestIntervalId", wireType)
			}
			m.RequestIntervalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestIntervalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
