// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consumer/oracleconsumer/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSetRequestInterval struct {
	OracleScriptId uint64                                   `protobuf:"varint,1,opt,name=oracle_script_id,json=oracleScriptId,proto3" json:"oracle_script_id,omitempty"`
	Calldata       []byte                                   `protobuf:"bytes,2,opt,name=calldata,proto3" json:"calldata,omitempty"`
	BlockInterval  uint64                                   `protobuf:"varint,3,opt,name=block_interval,json=blockInterval,proto3" json:"block_interval,omitempty"`
	AskCount       uint64                                   `protobuf:"varint,4,opt,name=ask_count,json=askCount,proto3" json:"ask_count,omitempty"`
	MinCount       uint64                                   `protobuf:"varint,5,opt,name=min_count,json=minCount,proto3" json:"min_count,omitempty"`
	FeeLimit       github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,6,rep,name=fee_limit,json=feeLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"fee_limit"`
	PrepareGas     uint64                                   `protobuf:"varint,7,opt,name=prepare_gas,json=prepareGas,proto3" json:"prepare_gas,omitempty"`
	ExecuteGas     uint64                                   `protobuf:"varint,8,opt,name=execute_gas,json=executeGas,proto3" json:"execute_gas,omitempty"`
	SourceChannel  string                                   `protobuf:"bytes,9,opt,name=source_channel,json=sourceChannel,proto3" json:"source_channel,omitempty"`
	Sender         string                                   `protobuf:"bytes,10,opt,name=sender,proto3" json:"sender,omitempty"`
}

func (m *MsgSetRequestInterval) Reset()         { *m = MsgSetRequestInterval{} }
func (m *MsgSetRequestInterval) String() string { return proto.CompactTextString(m) }
func (*MsgSetRequestInterval) ProtoMessage()    {}
func (*MsgSetRequestInterval) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6011a1e590132c7, []int{0}
}
func (m *MsgSetRequestInterval) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRequestInterval) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRequestInterval.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRequestInterval) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRequestInterval.Merge(m, src)
}
func (m *MsgSetRequestInterval) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRequestInterval) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRequestInterval.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRequestInterval proto.InternalMessageInfo

func (m *MsgSetRequestInterval) GetOracleScriptId() uint64 {
	if m != nil {
		return m.OracleScriptId
	}
	return 0
}

func (m *MsgSetRequestInterval) GetCalldata() []byte {
	if m != nil {
		return m.Calldata
	}
	return nil
}

func (m *MsgSetRequestInterval) GetBlockInterval() uint64 {
	if m != nil {
		return m.BlockInterval
	}
	return 0
}

func (m *MsgSetRequestInterval) GetAskCount() uint64 {
	if m != nil {
		return m.AskCount
	}
	return 0
}

func (m *MsgSetRequestInterval) GetMinCount() uint64 {
	if m != nil {
		return m.MinCount
	}
	return 0
}

func (m *MsgSetRequestInterval) GetFeeLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.FeeLimit
	}
	return nil
}

func (m *MsgSetRequestInterval) GetPrepareGas() uint64 {
	if m != nil {
		return m.PrepareGas
	}
	return 0
}

func (m *MsgSetRequestInterval) GetExecuteGas() uint64 {
	if m != nil {
		return m.ExecuteGas
	}
	return 0
}

func (m *MsgSetRequestInterval) GetSourceChannel() string {
	if m != nil {
		return m.SourceChannel
	}
	return ""
}

func (m *MsgSetRequestInterval) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

type MsgSetRequestIntervalResponse struct {
	RequestIntervalId uint64 `protobuf:"varint,1,opt,name=request_interval_id,json=requestIntervalId,proto3" json:"request_interval_id,omitempty"`
}

func (m *MsgSetRequestIntervalResponse) Reset()         { *m = MsgSetRequestIntervalResponse{} }
func (m *MsgSetRequestIntervalResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetRequestIntervalResponse) ProtoMessage()    {}
func (*MsgSetRequestIntervalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6011a1e590132c7, []int{1}
}
func (m *MsgSetRequestIntervalResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetRequestIntervalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetRequestIntervalResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetRequestIntervalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetRequestIntervalResponse.Merge(m, src)
}
func (m *MsgSetRequestIntervalResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetRequestIntervalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetRequestIntervalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetRequestIntervalResponse proto.InternalMessageInfo

func (m *MsgSetRequestIntervalResponse) GetRequestIntervalId() uint64 {
	if m != nil {
		return m.RequestIntervalId
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgSetRequestInterval)(nil), "consumer.oracleconsumer.MsgSetRequestInterval")
	proto.RegisterType((*MsgSetRequestIntervalResponse)(nil), "consumer.oracleconsumer.MsgSetRequestIntervalResponse")
}

func init() { proto.RegisterFile("consumer/oracleconsumer/tx.proto", fileDescriptor_d6011a1e590132c7) }

var fileDescriptor_d6011a1e590132c7 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x63, 0x52, 0x42, 0xb2, 0xa5, 0x11, 0x98, 0x7f, 0x26, 0x08, 0x27, 0xaa, 0x54, 0xc9,
	0x17, 0xd6, 0xb4, 0x48, 0x48, 0x5c, 0x9b, 0x03, 0x8a, 0x44, 0x85, 0xe4, 0xde, 0xb8, 0x58, 0x9b,
	0xf5, 0xd4, 0x59, 0xc5, 0xde, 0x35, 0x3b, 0xeb, 0x2a, 0x48, 0xdc, 0x78, 0x01, 0x5e, 0x03, 0x9e,
	0xa4, 0xc7, 0x1e, 0x39, 0x01, 0x4a, 0x5e, 0x04, 0xd9, 0xeb, 0x1a, 0x55, 0x84, 0x43, 0x4f, 0xc9,
	0x7c, 0xdf, 0x6f, 0x67, 0x67, 0x76, 0xc6, 0x64, 0xc2, 0x95, 0xc4, 0x32, 0x07, 0x1d, 0x2a, 0xcd,
	0x78, 0x06, 0x6d, 0x68, 0x56, 0xb4, 0xd0, 0xca, 0x28, 0xf7, 0xc9, 0x95, 0x44, 0xaf, 0x13, 0xa3,
	0x87, 0xa9, 0x4a, 0x55, 0xcd, 0x84, 0xd5, 0x3f, 0x8b, 0x8f, 0x7c, 0xae, 0x30, 0x57, 0x18, 0xce,
	0x19, 0x42, 0x78, 0x7e, 0x38, 0x07, 0xc3, 0x0e, 0x43, 0xae, 0x84, 0xb4, 0xfe, 0xfe, 0xb7, 0x2e,
	0x79, 0x74, 0x82, 0xe9, 0x29, 0x98, 0x08, 0x3e, 0x96, 0x80, 0x66, 0x26, 0x0d, 0xe8, 0x73, 0x96,
	0xb9, 0x01, 0xb9, 0x67, 0x6f, 0x88, 0x91, 0x6b, 0x51, 0x98, 0x58, 0x24, 0x9e, 0x33, 0x71, 0x82,
	0x9d, 0x68, 0x68, 0xf5, 0xd3, 0x5a, 0x9e, 0x25, 0xee, 0x88, 0xf4, 0x39, 0xcb, 0xb2, 0x84, 0x19,
	0xe6, 0xdd, 0x9a, 0x38, 0xc1, 0xdd, 0xa8, 0x8d, 0xdd, 0x03, 0x32, 0x9c, 0x67, 0x8a, 0x2f, 0x63,
	0xd1, 0xe4, 0xf5, 0xba, 0x75, 0x8e, 0xbd, 0x5a, 0x6d, 0x2f, 0x7b, 0x46, 0x06, 0x0c, 0x97, 0x31,
	0x57, 0xa5, 0x34, 0xde, 0x4e, 0x4d, 0xf4, 0x19, 0x2e, 0xa7, 0x55, 0x5c, 0x99, 0xb9, 0x90, 0x8d,
	0x79, 0xdb, 0x9a, 0xb9, 0x90, 0xd6, 0x5c, 0x90, 0xc1, 0x19, 0x40, 0x9c, 0x89, 0x5c, 0x18, 0xaf,
	0x37, 0xe9, 0x06, 0xbb, 0x47, 0x4f, 0xa9, 0x6d, 0x9a, 0x56, 0x4d, 0xd3, 0xa6, 0x69, 0x3a, 0x55,
	0x42, 0x1e, 0xbf, 0xbc, 0xf8, 0x39, 0xee, 0x7c, 0xff, 0x35, 0x0e, 0x52, 0x61, 0x16, 0xe5, 0x9c,
	0x72, 0x95, 0x87, 0xcd, 0x0b, 0xd9, 0x9f, 0x17, 0x98, 0x2c, 0x43, 0xf3, 0xa9, 0x00, 0xac, 0x0f,
	0x60, 0xd4, 0x3f, 0x03, 0x78, 0x57, 0x25, 0x77, 0xc7, 0x64, 0xb7, 0xd0, 0x50, 0x30, 0x0d, 0x71,
	0xca, 0xd0, 0xbb, 0x53, 0x17, 0x42, 0x1a, 0xe9, 0x2d, 0xc3, 0x0a, 0x80, 0x15, 0xf0, 0xd2, 0x58,
	0xa0, 0x6f, 0x81, 0x46, 0xaa, 0x80, 0x03, 0x32, 0x44, 0x55, 0x6a, 0x0e, 0x31, 0x5f, 0x30, 0x29,
	0x21, 0xf3, 0x06, 0x13, 0x27, 0x18, 0x44, 0x7b, 0x56, 0x9d, 0x5a, 0xd1, 0x7d, 0x4c, 0x7a, 0x08,
	0x32, 0x01, 0xed, 0x91, 0xda, 0x6e, 0xa2, 0xfd, 0xf7, 0xe4, 0xf9, 0xd6, 0x51, 0x45, 0x80, 0x85,
	0x92, 0x08, 0x2e, 0x25, 0x0f, 0xb4, 0xb5, 0xda, 0xe7, 0xfe, 0x3b, 0xb5, 0xfb, 0xfa, 0xfa, 0xa9,
	0x59, 0x72, 0xf4, 0xc5, 0x21, 0xdd, 0x13, 0x4c, 0xdd, 0xcf, 0xc4, 0xdd, 0xb2, 0x00, 0x94, 0xfe,
	0x67, 0xd5, 0xe8, 0xd6, 0x2a, 0x46, 0xaf, 0x6f, 0xc6, 0x5f, 0x55, 0x7d, 0xfc, 0xe6, 0x62, 0xed,
	0x3b, 0x97, 0x6b, 0xdf, 0xf9, 0xbd, 0xf6, 0x9d, 0xaf, 0x1b, 0xbf, 0x73, 0xb9, 0xf1, 0x3b, 0x3f,
	0x36, 0x7e, 0xe7, 0xc3, 0xb8, 0x5d, 0xff, 0xd5, 0x3f, 0xdf, 0x43, 0x35, 0xa2, 0x79, 0xaf, 0x5e,
	0xe2, 0x57, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x10, 0x8f, 0xd2, 0x5c, 0x37, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SetRequestInterval(ctx context.Context, in *MsgSetRequestInterval, opts ...grpc.CallOption) (*MsgSetRequestIntervalResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SetRequestInterval(ctx context.Context, in *MsgSetRequestInterval, opts ...grpc.CallOption) (*MsgSetRequestIntervalResponse, error) {
	out := new(MsgSetRequestIntervalResponse)
	err := c.cc.Invoke(ctx, "/consumer.oracleconsumer.Msg/SetRequestInterval", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SetRequestInterval(context.Context, *MsgSetRequestInterval) (*MsgSetRequestIntervalResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SetRequestInterval(ctx context.Context, req *MsgSetRequestInterval) (*MsgSetRequestIntervalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetRequestInterval not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SetRequestInterval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetRequestInterval)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetRequestInterval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/consumer.oracleconsumer.Msg/SetRequestInterval",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetRequestInterval(ctx, req.(*MsgSetRequestInterval))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "consumer.oracleconsumer.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetRequestInterval",
			Handler:    _Msg_SetRequestInterval_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "consumer/oracleconsumer/tx.proto",
}

func (m *MsgSetRequestInterval) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRequestInterval) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRequestInterval) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.SourceChannel) > 0 {
		i -= len(m.SourceChannel)
		copy(dAtA[i:], m.SourceChannel)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SourceChannel)))
		i--
		dAtA[i] = 0x4a
	}
	if m.ExecuteGas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ExecuteGas))
		i--
		dAtA[i] = 0x40
	}
	if m.PrepareGas != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PrepareGas))
		i--
		dAtA[i] = 0x38
	}
	if len(m.FeeLimit) > 0 {
		for iNdEx := len(m.FeeLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeeLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.MinCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MinCount))
		i--
		dAtA[i] = 0x28
	}
	if m.AskCount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.AskCount))
		i--
		dAtA[i] = 0x20
	}
	if m.BlockInterval != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockInterval))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Calldata) > 0 {
		i -= len(m.Calldata)
		copy(dAtA[i:], m.Calldata)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Calldata)))
		i--
		dAtA[i] = 0x12
	}
	if m.OracleScriptId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.OracleScriptId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetRequestIntervalResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetRequestIntervalResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetRequestIntervalResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RequestIntervalId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RequestIntervalId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSetRequestInterval) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.OracleScriptId != 0 {
		n += 1 + sovTx(uint64(m.OracleScriptId))
	}
	l = len(m.Calldata)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockInterval != 0 {
		n += 1 + sovTx(uint64(m.BlockInterval))
	}
	if m.AskCount != 0 {
		n += 1 + sovTx(uint64(m.AskCount))
	}
	if m.MinCount != 0 {
		n += 1 + sovTx(uint64(m.MinCount))
	}
	if len(m.FeeLimit) > 0 {
		for _, e := range m.FeeLimit {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.PrepareGas != 0 {
		n += 1 + sovTx(uint64(m.PrepareGas))
	}
	if m.ExecuteGas != 0 {
		n += 1 + sovTx(uint64(m.ExecuteGas))
	}
	l = len(m.SourceChannel)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetRequestIntervalResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.RequestIntervalId != 0 {
		n += 1 + sovTx(uint64(m.RequestIntervalId))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSetRequestInterval) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRequestInterval: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRequestInterval: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OracleScriptId", wireType)
			}
			m.OracleScriptId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OracleScriptId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Calldata", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Calldata = append(m.Calldata[:0], dAtA[iNdEx:postIndex]...)
			if m.Calldata == nil {
				m.Calldata = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockInterval", wireType)
			}
			m.BlockInterval = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockInterval |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AskCount", wireType)
			}
			m.AskCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AskCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCount", wireType)
			}
			m.MinCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeLimit = append(m.FeeLimit, types.Coin{})
			if err := m.FeeLimit[len(m.FeeLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepareGas", wireType)
			}
			m.PrepareGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PrepareGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecuteGas", wireType)
			}
			m.ExecuteGas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecuteGas |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetRequestIntervalResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetRequestIntervalResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetRequestIntervalResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestIntervalId", wireType)
			}
			m.RequestIntervalId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RequestIntervalId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
