name: Tests
on: push

jobs:
  chain-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19.1'

      - name: Run chain tests
        run: go test ./...
