name: Tests
on: pull_request

jobs:
  chain-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.9'

      - name: Run chain tests
        run: go test ./...
